export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';


export const ADDUSER_REQUESTED = 'ADDUSER_REQUESTED';
export const ADDUSER_SUCCESS = 'ADDUSER_SUCCESS';
export const ADDUSER_ERROR = 'ADDUSER_ERROR';


export const GETALL_USERS = 'GETALL_USERS';
export const RECEIVEALL_USERS = 'RECEIVEALL_USERS';


export const GETALL_POLLS = 'GETALL_POLLS';
export const RECEIVEDALL_POLLS = 'RECEIVEDALL_POLLS';


export const ADD_POLL = 'ADD_POLL';
export const REMOVE_OPTION = 'REMOVE_OPTION';
export const ADDPOLL_REQUESTED = 'ADDPOLL_REQUESTED';
export const ADDPOLL_SUCCESS = 'ADDPOLL_SUCCESS';
export const ADDPOLL_ERROR = 'ADDPOLL_ERROR';

export const REQUESTREMOVE_POLL = 'REQUESTREMOVE_POLL';
export const REMOVE_POLL = 'REMOVE_POLL';

export const REQUESTEDIT_TITLE = 'REQUESTEDIT_TITLE';
export const SUCCESSEDIT_TITLE = 'SUCCESSEDIT_TITLE';


export const REQUESTREMOVE_POLLOPTION = 'REQUESTREMOVE_POLLOPTION';
export const REMOVE_POLLOPTION = 'REMOVE_POLLOPTION';

export const REQUESTADD_NEWOPTION = 'REQUESTADD_NEWOPTION';
export const SUCESSADD_NEWOPTION = 'SUCESSADD_NEWOPTION';
export const ERRORADD_NEWOPTION = 'ERRORADD_NEWOPTION';


export const REQUEST_VOTE = 'REQUEST_VOTE';
export const SUCESS_VOTE = 'SUCESS_VOTE';
